let token=localStorage.getItem("gaming_token")||"";
let currentUser=null;
let settings={};
let summary=null;
const $=s=>document.querySelector(s);
const money=n=>new Intl.NumberFormat("vi-VN").format(Number(n)||0)+"đ";
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
function toast(msg){const e=$("#toast");e.textContent=msg;e.className="toast show";setTimeout(()=>e.className="toast",2500)}
async function api(url,opts={}){opts.headers={...(opts.headers||{}),"Content-Type":"application/json",...(token?{Authorization:"Bearer "+token}:{})};const r=await fetch(url,opts);const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Có lỗi xảy ra");return d}
async function boot(){try{settings=await fetch("/api/config").then(r=>r.json());applyTheme();currentUser=await api("/api/me");summary=await api("/api/account/summary");renderAll();$("#accountLoading").classList.add("hidden");$("#accountSections").classList.remove("hidden")}catch(e){localStorage.removeItem("gaming_token");token="";$("#accountLoading").innerHTML=`<div class="empty-account"><div class="empty-icon">◉</div><h3>Bạn chưa đăng nhập</h3><p>Hãy đăng nhập tài khoản để xem ví, đơn hàng và thông tin cá nhân.</p><a href="/" class="primary-wide link-wide">Quay về shop để đăng nhập</a></div>`}}
function applyTheme(){document.title=(settings.shopName||"Gaming Shop")+" — Tài khoản";const r=document.documentElement;for(const [k,v] of Object.entries({primary:settings.primary,accent:settings.accent,pageBg:settings.pageBg,cardBg:settings.cardBg,text:settings.text,muted:settings.muted,footerBg:settings.footerBg})){if(v)r.style.setProperty("--"+k.replace(/[A-Z]/g,m=>"-"+m.toLowerCase()),v)}$("#shopName").textContent=settings.shopName||"Gaming Shop";$("#shopTagline").textContent=settings.shopTagline||"Marketplace";$("#brandBadge").innerHTML=settings.logo?`<img src="${settings.logo}" alt="">`:(settings.shopName||"G").slice(0,1).toUpperCase();$("#favicon").href=settings.favicon||settings.logo||"data:,"}
function renderAll(){const u=currentUser;const initial=(u.name||"U").slice(0,1).toUpperCase();$("#accountName").textContent=u.name;$("#accountBalance").textContent=money(u.balance);$("#avatarLetter").textContent=initial;$("#largeAvatar").textContent=initial;$("#sideName").textContent=u.name;$("#sideBalance").textContent=money(u.balance);$("#heroBalance").textContent=money(u.balance);$("#totalTopup").textContent=money(summary.totals.approvedTopup);$("#totalSpent").textContent=money(summary.totals.spent);$("#discountPercent").textContent=`${Number(u.discountPercent||0)}%`;$("#securityEmail").textContent=u.email;renderProfile();renderOrders();renderTransactions();renderSupport();$("#refCode").textContent=(u.id||"").slice(0,8).toUpperCase()||"---";$("#cartCount").textContent=(JSON.parse(localStorage.getItem("gaming_cart")||"[]")).reduce((s,i)=>s+i.qty,0)}
function renderProfile(){const u=currentUser;const last=u.lastLoginAt?new Date(u.lastLoginAt).toLocaleString("vi-VN"):"Chưa ghi nhận";const created=u.createdAt?new Date(u.createdAt).toLocaleString("vi-VN"):"—";const device=navigator.userAgent;const items=[["Tên đăng nhập",u.name||"Chưa cập nhật"],["Địa chỉ Email",u.email],["Số điện thoại",u.phone||"Chưa cập nhật"],["Họ và Tên",u.fullName||"Chưa cập nhật"],["Telegram",u.telegram||"Chưa liên kết"],["Thiết bị",device],["Đăng ký vào lúc",created],["Đăng nhập gần nhất",last]];$("#profileGrid").innerHTML=items.map(([l,v])=>`<div class="info-item"><span>▣ ${esc(l)}</span><b>${esc(v)}</b></div>`).join("")}
function renderOrders(){const list=summary.orders||[];$("#orderCountBadge").textContent=list.length;$("#ordersList").innerHTML=list.length?list.map(o=>`<div class="order-row"><div><b>${esc(o.id)}</b><small>${new Date(o.createdAt).toLocaleString("vi-VN")} · ${o.items?.length||0} mục</small></div><div class="order-row-right"><strong>${money(o.total)}</strong><span class="status-badge ${o.status==='completed'||o.status==='paid'?'green':''}">${esc(o.status)}</span></div></div>`).join(""):`<div class="empty-account"><h3>Chưa có đơn hàng</h3><p>Những đơn hàng bạn thanh toán sẽ xuất hiện tại đây.</p></div>`}
function renderTransactions(){const list=summary.transactions||[];$("#balanceList").innerHTML=list.length?list.map(t=>transactionRow(t)).join(""):`<div class="empty-account"><h3>Chưa có biến động số dư</h3><p>Lịch sử nạp tiền và thanh toán sẽ hiển thị ở đây.</p></div>`;$("#activityList").innerHTML=list.slice(0,20).map(t=>transactionRow(t)).join("")||`<div class="empty-account"><h3>Chưa có hoạt động</h3><p>Hoạt động gần đây sẽ hiển thị tại đây.</p></div>`}
function transactionRow(t){const positive=t.amount>=0;return `<div class="transaction-row"><div><b>${esc(t.title)}</b><small>${esc(t.id)} · ${new Date(t.createdAt).toLocaleString("vi-VN")} · ${esc(t.status)}</small></div><div class="transaction-row-right"><strong style="color:${positive?'#39d499':'#ff6b6b'}">${positive?'+':''}${money(Math.abs(t.amount))}</strong></div></div>`}
function renderSupport(){const links=[["Discord",settings.discord],["Facebook",settings.facebook],["Telegram",settings.telegram],["Email",settings.supportEmail?`mailto:${settings.supportEmail}`:""]].filter(x=>x[1]);$("#supportCopy").textContent=`Hỗ trợ: ${settings.supportEmail||"chưa cấu hình"}${settings.supportPhone?` · ${settings.supportPhone}`:""}`;$("#supportLinks").innerHTML=links.map(([n,u])=>`<a href="${esc(u)}" target="_blank" rel="noopener">${esc(n)}</a>`).join("")||`<span style="color:#777;font-size:9px">Shop chưa cấu hình kênh hỗ trợ.</span>`}
function switchSection(name){document.querySelectorAll(".account-section").forEach(s=>s.classList.toggle("hidden",s.dataset.section!==name));document.querySelectorAll(".side-link").forEach(b=>b.classList.toggle("active",b.dataset.section===name));window.scrollTo({top:0,behavior:"smooth"})}
function openModal(html){$("#modalCard").innerHTML=html;$("#modal").classList.remove("hidden")};function closeModal(){$("#modal").classList.add("hidden")}
function openProfileEditor(){const u=currentUser;openModal(`<div class="modal-headline"><h3>Chỉnh sửa thông tin</h3><button class="modal-close" onclick="closeModal()">×</button></div><form onsubmit="saveProfile(event)"><div class="profile-form-grid"><label>Tên đăng nhập<input name="name" value="${esc(u.name)}" required></label><label>Email<input value="${esc(u.email)}" disabled></label><label>Họ và tên<input name="fullName" value="${esc(u.fullName||"")}" placeholder="Nguyễn Văn A"></label><label>Số điện thoại<input name="phone" value="${esc(u.phone||"")}" placeholder="09xxxxxxxx"></label><label>Telegram<input name="telegram" value="${esc(u.telegram||"")}" placeholder="@username"></label></div><div class="modal-actions"><button type="button" class="edit-btn" onclick="closeModal()">Hủy</button><button class="edit-btn">Lưu thay đổi</button></div></form>`) }
async function saveProfile(e){e.preventDefault();const f=e.target;try{currentUser=await api("/api/account/profile",{method:"PUT",body:JSON.stringify({name:f.name.value,fullName:f.fullName.value,phone:f.phone.value,telegram:f.telegram.value})});summary.user=currentUser;renderAll();closeModal();toast("Đã cập nhật thông tin") }catch(err){toast(err.message)}}
async function changePassword(e){e.preventDefault();const f=e.target;if(f.newPassword.value!==f.confirmPassword.value)return toast("Mật khẩu nhập lại không khớp");try{await api("/api/account/password",{method:"POST",body:JSON.stringify({currentPassword:f.currentPassword.value,newPassword:f.newPassword.value})});f.reset();toast("Đã đổi mật khẩu")}catch(err){toast(err.message)}}
function logout(){localStorage.removeItem("gaming_token");window.location.href="/"}
boot();
