let token=localStorage.getItem("gaming_token")||localStorage.getItem("gaming_admin_token")||"";
let currentUser=null,settings={},summary=null,security={loginAlerts:true,orderProtection:false,twoFactorEnabled:false},pending2FA=null;
const $=s=>document.querySelector(s);const money=n=>new Intl.NumberFormat("vi-VN").format(Number(n)||0)+"đ";const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
function toast(msg){const e=$("#toast");e.textContent=msg;e.className="toast show";clearTimeout(window.__tt);window.__tt=setTimeout(()=>e.className="toast",2500)}
async function api(url,opts={}){opts.headers={...(opts.headers||{}),"Content-Type":"application/json",...(token?{Authorization:"Bearer "+token}: {})};const r=await fetch(url,opts);const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Có lỗi xảy ra");return d}
function applyTheme(){const r=document.documentElement;for(const [k,v] of Object.entries({primary:settings.primary,accent:settings.accent,pageBg:settings.pageBg,cardBg:settings.cardBg,text:settings.text,muted:settings.muted,footerBg:settings.footerBg}))if(v)r.style.setProperty("--"+k.replace(/[A-Z]/g,m=>"-"+m.toLowerCase()),v);const bodyFont=["DM Sans","Inter","Manrope","Poppins"].includes(settings.fontBody)?settings.fontBody:"DM Sans";const headFont=["Space Grotesk","DM Sans","Inter","Manrope","Poppins"].includes(settings.fontHeading)?settings.fontHeading:"Space Grotesk";r.style.setProperty("--font-body",`"${bodyFont}",system-ui,sans-serif`);r.style.setProperty("--font-heading",`"${headFont}",system-ui,sans-serif`);document.title=(settings.shopName||"Gaming Shop")+" — Tài khoản";$("#shopName").textContent=settings.shopName||"Gaming Shop";$("#shopTagline").textContent=settings.shopTagline||"Marketplace";$("#brandBadge").innerHTML=settings.logo?`<img src="${settings.logo}" alt="">`:(settings.shopName||"G").slice(0,1).toUpperCase();$("#favicon").href=settings.favicon||settings.logo||"data:,"}
async function boot(){try{settings=await fetch("/api/config").then(r=>r.json());applyTheme();currentUser=await api("/api/me");summary=await api("/api/account/summary");security=await api("/api/account/security");renderAll();$("#accountLoading").classList.add("hidden");$("#accountSections").classList.remove("hidden")}catch(e){localStorage.removeItem("gaming_token");token="";$("#accountLoading").innerHTML=`<div class="empty-account"><div class="empty-icon">◉</div><h3>Bạn chưa đăng nhập</h3><p>Hãy đăng nhập tài khoản để xem thông tin cá nhân.</p><a href="/" class="primary-wide link-wide">Quay về shop để đăng nhập</a></div>`}}
function renderAll(){const u=currentUser;const initial=(u.name||"U").slice(0,1).toUpperCase();$("#accountName").textContent=u.name;$("#accountBalance").textContent=money(u.balance);$("#avatarLetter").textContent=initial;$("#largeAvatar").textContent=initial;$("#sideName").textContent=u.name;$("#sideBalance").textContent=money(u.balance);$("#heroBalance").textContent=money(u.balance);$("#totalTopup").textContent=money(summary.totals.approvedTopup);$("#totalSpent").textContent=money(summary.totals.spent);$("#discountPercent").textContent=`${Number(u.discountPercent||0)}%`;$("#orderCountBadge").textContent=summary.orders.length;$("#refCode").textContent=(u.id||"").slice(0,8).toUpperCase()||"---";$("#cartCount").textContent=(JSON.parse(localStorage.getItem("gaming_cart")||"[]")).reduce((s,i)=>s+i.qty,0);renderProfile();renderOrders();renderTransactions();renderActivity();renderSupport();renderSecurity();}
function renderProfile(){const u=currentUser;const items=[["Tên đăng nhập",u.name||"Chưa cập nhật"],["Địa chỉ Email",u.email],["Số điện thoại",u.phone||"Chưa cập nhật"],["Họ và Tên",u.fullName||"Chưa cập nhật"],["Telegram",u.telegram||"Chưa liên kết"],["Thiết bị",navigator.userAgent],["Đăng ký vào lúc",u.createdAt?new Date(u.createdAt).toLocaleString("vi-VN"):"—"],["Đăng nhập gần nhất",u.lastLoginAt?new Date(u.lastLoginAt).toLocaleString("vi-VN"):"Chưa ghi nhận"]];$("#profileGrid").innerHTML=items.map(([l,v])=>`<div class="info-item"><span>▣ ${esc(l)}</span><b>${esc(v)}</b></div>`).join("")}
function renderOrders(){const list=summary.orders||[];$("#ordersList").innerHTML=list.length?list.map(o=>`<div class="order-row"><div><b>${esc(o.id)}</b><small>${new Date(o.createdAt).toLocaleString("vi-VN")} · ${(o.items||[]).map(i=>esc(i.name+" — "+i.variantName)).join(", ")}</small></div><div class="order-row-right"><strong>${money(o.total)}</strong><span class="status-badge ${o.status==='completed'||o.status==='paid'?'green':''}">${esc(o.status)}</span></div></div>`).join(""):`<div class="empty-account"><h3>Chưa có đơn hàng</h3><p>Những đơn hàng bạn thanh toán sẽ xuất hiện tại đây.</p></div>`}
function transactionRow(t){const positive=t.amount>=0;return `<div class="transaction-row"><div><b>${esc(t.title)}</b><small>${esc(t.id)} · ${new Date(t.createdAt).toLocaleString("vi-VN")} · ${esc(t.status)}</small></div><div class="transaction-row-right"><strong style="color:${positive?'#39d499':'#ff6b6b'}">${positive?'+':''}${money(Math.abs(t.amount))}</strong></div></div>`}
function renderTransactions(){$("#balanceList").innerHTML=(summary.transactions||[]).map(transactionRow).join("")||`<div class="empty-account"><h3>Chưa có biến động số dư</h3><p>Lịch sử nạp tiền và thanh toán sẽ hiển thị tại đây.</p></div>`}
function renderActivity(){const list=summary.activities||[];$("#activityList").innerHTML=list.map(a=>`<div class="transaction-row"><div><b>${esc(a.action)}</b><small>${new Date(a.createdAt).toLocaleString("vi-VN")}</small></div><div class="transaction-row-right"><small>${esc(a.ip||"")}</small></div></div>`).join("")||`<div class="empty-account"><h3>Chưa có hoạt động</h3><p>Hoạt động gần đây sẽ hiển thị tại đây.</p></div>`}
function renderSupport(){const links=[["Discord",settings.discord],["Facebook",settings.facebook],["Telegram",settings.telegram],["Email",settings.supportEmail?`mailto:${settings.supportEmail}`:""]].filter(x=>x[1]);$("#supportCopy").textContent=`Hỗ trợ: ${settings.supportEmail||"chưa cấu hình"}${settings.supportPhone?` · ${settings.supportPhone}`:""}`;$("#supportLinks").innerHTML=links.map(([n,u])=>`<a href="${esc(u)}" target="_blank" rel="noopener">${esc(n)}</a>`).join("")||`<span style="color:#777;font-size:9px">Shop chưa cấu hình kênh hỗ trợ.</span>`}
function renderSecurity(){const box=$("#securityToggles");box.innerHTML=`<div class="security-row"><div><b>Xác minh OTP qua Email</b><small>Yêu cầu xác minh thêm qua email khi đăng nhập</small></div><button class="security-toggle disabled" title="Chưa triển khai email OTP"><i></i></button></div><div class="security-row"><div><b>Thông báo đăng nhập</b><small>Nhận email thông báo mỗi khi có đăng nhập thành công</small></div><button class="security-toggle ${security.loginAlerts!==false?'on':''}" onclick="toggleSecurity('loginAlerts',this)"><i></i></button></div><div class="security-row"><div><b>Bảo vệ đơn hàng</b><small>Chỉ xem đơn hàng từ trình duyệt/IP đã mua</small></div><button class="security-toggle ${security.orderProtection?'on':''}" onclick="toggleSecurity('orderProtection',this)"><i></i></button></div>`;const g=$("#googleAuthBox");if(security.twoFactorEnabled){g.innerHTML=`<div class="google-enabled"><div><b>Xác thực 2 lớp (2FA)</b><small>Google Authenticator đang bảo vệ tài khoản của bạn.</small></div><button class="danger-small" onclick="openDisable2FA()">Tắt 2FA</button></div><div class="security-note success-note">✓ 2FA đã được bật. Mỗi lần đăng nhập sẽ cần mã 6 số từ ứng dụng Authenticator.</div>`}else{g.innerHTML=`<div class="google-setup"><div class="security-row google-title-row"><div><b>▦ Xác thực 2 lớp (2FA)</b><small>Sử dụng Google Authenticator để bảo vệ tài khoản.</small></div><button class="security-toggle" onclick="setup2FA()"><i></i></button></div>${pending2FA?`<div class="qr-box"><div class="qr-frame"><img src="${pending2FA.qrUrl}" alt="QR Google Authenticator"></div><div class="secret-line"><span>Khóa bí mật</span><code>${esc(pending2FA.secret)}</code></div><form class="otp-confirm" onsubmit="confirm2FA(event)"><input name="code" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" placeholder="Mã 6 chữ số" required><button class="primary-wide">✓ Xác nhận</button></form></div>`:`<button class="primary-wide link-wide" onclick="setup2FA()">Bật Google Authenticator</button>`}</div><div class="security-note"><b>✓ Hướng dẫn</b><br>1. Tải Google Authenticator trên điện thoại.<br>2. Quét QR để liên kết tài khoản.<br>3. Nhập mã 6 số đang hiển thị để xác minh.<br>4. Không bật đồng thời OTP Mail và Google Authenticator.</div>`}}
function toggleSecurity(key,btn){security[key]=!security[key];btn.classList.toggle("on",security[key])}
async function saveSecurity(){try{security=await api("/api/account/security",{method:"PUT",body:JSON.stringify({loginAlerts:security.loginAlerts,orderProtection:security.orderProtection})});renderSecurity();toast("Đã lưu thay đổi bảo mật")}catch(e){toast(e.message)}}
async function setup2FA(){try{pending2FA=await api("/api/account/2fa/setup",{method:"POST"});renderSecurity();toast("Đã tạo QR. Hãy quét bằng Google Authenticator.")}catch(e){toast(e.message)}}
async function confirm2FA(e){e.preventDefault();try{const code=new FormData(e.target).get("code");currentUser=await api("/api/account/2fa/confirm",{method:"POST",body:JSON.stringify({code})});pending2FA=null;security=await api("/api/account/security");summary=await api("/api/account/summary");renderAll();toast("Đã bật Google Authenticator")}catch(err){toast(err.message)}}
function openDisable2FA(){openModal(`<div class="modal-headline"><h3>Tắt Google Authenticator</h3><button class="modal-close" onclick="closeModal()">×</button></div><p style="color:#aaa;font-size:10px">Nhập mật khẩu hiện tại và mã 6 số trong Authenticator.</p><form class="account-form" onsubmit="disable2FA(event)"><label>Mật khẩu<input name="password" type="password" required></label><label>Mã Authenticator<input name="code" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" required></label><div class="modal-actions"><button type="button" class="edit-btn" onclick="closeModal()">Hủy</button><button class="edit-btn">Tắt 2FA</button></div></form>`)}
async function disable2FA(e){e.preventDefault();try{const f=new FormData(e.target);currentUser=await api("/api/account/2fa/disable",{method:"POST",body:JSON.stringify({password:f.get("password"),code:f.get("code")})});security=await api("/api/account/security");closeModal();renderAll();toast("Đã tắt 2FA")}catch(err){toast(err.message)}}
function switchSection(name){document.querySelectorAll(".account-section").forEach(s=>s.classList.toggle("hidden",s.dataset.section!==name));document.querySelectorAll(".side-link").forEach(b=>b.classList.toggle("active",b.dataset.section===name));window.scrollTo({top:0,behavior:"smooth"})}
function openModal(html){$("#modalCard").innerHTML=html;$("#modal").classList.remove("hidden")};function closeModal(){$("#modal").classList.add("hidden")}
function openProfileEditor(){const u=currentUser;openModal(`<div class="modal-headline"><h3>Chỉnh sửa thông tin</h3><button class="modal-close" onclick="closeModal()">×</button></div><form onsubmit="saveProfile(event)"><div class="profile-form-grid"><label>Tên đăng nhập<input name="name" value="${esc(u.name)}" required></label><label>Email<input value="${esc(u.email)}" disabled></label><label>Họ và tên<input name="fullName" value="${esc(u.fullName||"")}" placeholder="Nguyễn Văn A"></label><label>Số điện thoại<input name="phone" value="${esc(u.phone||"")}" placeholder="09xxxxxxxx"></label><label>Telegram<input name="telegram" value="${esc(u.telegram||"")}" placeholder="@username"></label></div><div class="modal-actions"><button type="button" class="edit-btn" onclick="closeModal()">Hủy</button><button class="edit-btn">Lưu thay đổi</button></div></form>`)}
async function saveProfile(e){e.preventDefault();const f=e.target;try{currentUser=await api("/api/account/profile",{method:"PUT",body:JSON.stringify({name:f.name.value,fullName:f.fullName.value,phone:f.phone.value,telegram:f.telegram.value})});summary.user=currentUser;renderAll();closeModal();toast("Đã cập nhật thông tin")}catch(err){toast(err.message)}}
async function changePassword(e){e.preventDefault();const f=e.target;if(f.newPassword.value!==f.confirmPassword.value)return toast("Mật khẩu nhập lại không khớp");try{await api("/api/account/password",{method:"POST",body:JSON.stringify({currentPassword:f.currentPassword.value,newPassword:f.newPassword.value})});f.reset();summary=await api("/api/account/summary");renderAll();toast("Đã đổi mật khẩu")}catch(err){toast(err.message)}}
function logout(){localStorage.removeItem("gaming_token");window.location.href="/"}
boot();
