let adminToken = localStorage.getItem("gaming_admin_token") || localStorage.getItem("gaming_token") || "";
let adminUser = null;
let products = [];
let settings = {};
let cache = { orders: [], topups: [] };
const $ = (s) => document.querySelector(s);
const esc = (s) => String(s ?? "").replace(/[&<>"']/g, m => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const money = (n) => new Intl.NumberFormat("vi-VN").format(Number(n)||0) + "đ";
const fmtDate = (s) => { try{return new Date(s).toLocaleString("vi-VN")}catch{return s||""} };
function toast(msg){const el=$("#toast");el.textContent=msg;el.className="toast show";clearTimeout(window.__tt);window.__tt=setTimeout(()=>el.className="toast",2600)}
async function api(url, opts={}){
  opts.headers={...(opts.headers||{}),"Content-Type":"application/json",...(adminToken?{Authorization:"Bearer "+adminToken}:{})};
  const r=await fetch(url,opts); const d=await r.json().catch(()=>({}));
  if(!r.ok) throw new Error(d.error||"Có lỗi xảy ra"); return d;
}
function fileToData(file){return new Promise((resolve,reject)=>{if(!file)return resolve("");if(file.size>4*1024*1024)return reject(new Error("Ảnh tối đa 4MB"));const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)})}

async function boot(){
  try{
    settings=await fetch("/api/config").then(r=>r.json());
    applyBrand();
    if(adminToken){try{adminUser=await api("/api/me"); if(adminUser.role!=="admin") throw new Error("Tài khoản không có quyền admin"); localStorage.setItem("gaming_admin_token",adminToken); showAdmin(); return;}catch(e){localStorage.removeItem("gaming_admin_token");adminToken="";}}
    showLogin();
  }catch(e){toast(e.message);showLogin()}
}
function applyBrand(){
  $("#sideShopName").textContent=settings.shopName||"Gaming Shop";
  const logo=settings.logo||""; $("#sideLogo").innerHTML=logo?`<img src="${logo}" style="width:100%;height:100%;object-fit:cover;border-radius:13px" alt="">`:(settings.shopName||"G").slice(0,1).toUpperCase();
  $("#adminFavicon").href=settings.favicon||settings.logo||"data:,";
  document.title=`Admin — ${settings.shopName||"Gaming Shop"}`;
}
function showLogin(){$("#loginView").classList.remove("hidden");$("#adminView").classList.add("hidden")}
function showAdmin(){$("#loginView").classList.add("hidden");$("#adminView").classList.remove("hidden");$("#adminName").textContent=adminUser.name||adminUser.email;$("#adminAvatar").textContent=(adminUser.name||"A").slice(0,1).toUpperCase();go("dashboard")}
$("#loginForm").addEventListener("submit",async e=>{e.preventDefault();const f=new FormData(e.target);try{const d=await fetch("/api/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(f))});const x=await d.json();if(!d.ok)throw new Error(x.error||"Đăng nhập thất bại");if(x.user.role!=="admin")throw new Error("Tài khoản này không phải Admin");adminToken=x.token;localStorage.setItem("gaming_admin_token",adminToken);adminUser=x.user;showAdmin()}catch(err){toast(err.message)}});
$("#logoutBtn").onclick=()=>{adminToken="";adminUser=null;localStorage.removeItem("gaming_admin_token");showLogin()};
document.querySelectorAll(".side-nav button").forEach(b=>b.addEventListener("click",()=>go(b.dataset.page)));
async function go(page){
  document.querySelectorAll(".side-nav button").forEach(b=>b.classList.toggle("active",b.dataset.page===page));
  const meta={dashboard:["DASHBOARD","Tổng quan"],products:["CATALOG","Sản phẩm"],orders:["SALES","Đơn hàng"],topups:["WALLET","Nạp tiền"],design:["CUSTOMIZER","Giao diện shop"]}[page]||["ADMIN","Quản trị"];
  $("#pageEyebrow").textContent=meta[0];$("#pageTitle").textContent=meta[1];
  try{if(page==="dashboard")return renderDashboard();if(page==="products")return renderProductsPage();if(page==="orders")return renderOrders();if(page==="topups")return renderTopups();if(page==="design")return renderDesign()}catch(e){toast(e.message)}
}

async function renderDashboard(){
  const [stats,orders,topups]=await Promise.all([api("/api/admin/stats"),api("/api/admin/orders"),api("/api/admin/topups")]);
  cache={orders,topups};
  $("#content").innerHTML=`<div class="grid-4">
    ${stat("Người dùng",stats.users,"Tài khoản khách")} ${stat("Sản phẩm",stats.products,"Đang bán trong catalog")} ${stat("Đơn hàng",stats.orders,"Tất cả trạng thái")} ${stat("Doanh thu",money(stats.revenue),"Đơn không bị hủy")}
  </div>
  <div class="two-panels">
    <section class="panel"><div class="panel-head"><h3>Đơn hàng gần đây</h3><button class="btn small" onclick="go('orders')">Xem tất cả</button></div><div class="list">${orders.slice(0,6).map(orderLine).join("")||`<div class="empty">Chưa có đơn hàng.</div>`}</div></section>
    <section class="panel"><div class="panel-head"><h3>Yêu cầu nạp tiền</h3><button class="btn small" onclick="go('topups')">Xem tất cả</button></div><div class="list">${topups.slice(0,6).map(topupLine).join("")||`<div class="empty">Chưa có yêu cầu.</div>`}</div></section>
  </div>`;
}
function stat(a,b,c){return `<div class="stat-card"><small>${esc(a.toUpperCase())}</small><strong>${esc(b)}</strong><p>${esc(c)}</p></div>`}
function orderLine(o){return `<div class="mini-line"><div><b>${esc(o.id)}</b><small>${fmtDate(o.createdAt)} · ${money(o.total)}</small></div><span class="status ${esc(o.status)}">${esc(o.status)}</span></div>`}
function topupLine(t){return `<div class="mini-line"><div><b>${esc(t.id)}</b><small>${money(t.amount)} · ${esc(t.method)}</small></div>${t.status==="pending"?`<button class="btn small" onclick="approveTopup('${esc(t.id)}')">Duyệt</button>`:`<span class="status ${esc(t.status)}">${esc(t.status)}</span>`}</div>`}

async function loadProducts(){products=await api("/api/products");return products}
async function renderProductsPage(){await loadProducts();$("#content").innerHTML=`<div class="page-toolbar"><div><div class="muted">Quản lý ảnh, giá, danh mục, badge và mô tả từng sản phẩm.</div></div><div class="row-actions"><div class="search"><input id="productSearch" placeholder="Tìm sản phẩm..." oninput="filterProductRows()"></div><button class="btn primary" onclick="productForm()">＋ Thêm sản phẩm</button></div></div><div id="productList" class="product-list">${products.map(productRow).join("")||`<div class="panel empty">Chưa có sản phẩm.</div>`}</div>`}
function productRow(p){return `<div class="product-row" data-search="${esc((p.name+" "+p.category).toLowerCase())}"><div class="product-main"><div class="thumb">${p.image?`<img src="${p.image}" alt="">`:`NO IMG`}</div><div><b>${esc(p.name)}</b><small>${esc(p.category)} · ${money(p.price)}${p.oldPrice?` · Giá cũ ${money(p.oldPrice)}`:""}</small><small>${esc(p.delivery||"Giao ngay")}${p.badge?` · ${esc(p.badge)}`:""}</small></div></div><div class="row-actions"><button class="btn small" onclick="productForm(${p.id})">Sửa</button><button class="btn small danger" onclick="deleteProduct(${p.id})">Xóa</button></div></div>`}
function filterProductRows(){const q=$("#productSearch").value.toLowerCase();document.querySelectorAll("#productList .product-row").forEach(x=>x.style.display=x.dataset.search.includes(q)?"":"none")}
function productForm(id=null){
  const p=id?products.find(x=>x.id===id):null; if(id&&!p)return;
  $("#content").innerHTML=`<div class="page-toolbar"><div><div class="muted">${p?"Chỉnh sửa sản phẩm":"Tạo sản phẩm mới"}</div></div><button class="btn" onclick="renderProductsPage()">← Quay lại</button></div>
  <form id="productForm" class="form-grid"><section class="design-card"><h3>Thông tin sản phẩm</h3><div class="field"><label>Tên sản phẩm<input name="name" value="${esc(p?.name||"")}" required></label></div><div class="field-grid"><div class="field"><label>Danh mục<input name="category" list="cats" value="${esc(p?.category||"")}" required></label></div><div class="field"><label>Badge<input name="badge" placeholder="HOT / NEW / SALE" value="${esc(p?.badge||"")}"></label></div></div><datalist id="cats">${(settings.categories||[]).map(c=>`<option value="${esc(c)}">`).join("")}</datalist><div class="field-grid"><div class="field"><label>Giá<input name="price" type="number" min="1" value="${p?.price||""}" required></label></div><div class="field"><label>Giá cũ<input name="oldPrice" type="number" min="0" value="${p?.oldPrice||0}"></label></div></div><div class="field"><label>Giao hàng<input name="delivery" value="${esc(p?.delivery||"Giao ngay")}"></label></div><div class="field"><label>Mô tả<textarea name="description">${esc(p?.description||"")}</textarea></label></div><div class="form-actions" style="margin-top:16px"><span class="muted">${p?`ID ${p.id}`:"Sản phẩm mới"}</span><button class="btn primary">${p?"Lưu thay đổi":"Tạo sản phẩm"}</button></div></section>
  <section class="design-card"><h3>Ảnh sản phẩm</h3><p class="muted">PNG/JPG/WebP/GIF, tối đa 4MB.</p><div class="upload"><input id="productImageFile" type="file" accept="image/png,image/jpeg,image/webp,image/gif"><div id="productPreview" class="preview">${p?.image?`<img src="${p.image}" alt="preview">`:`Chưa chọn ảnh`}</div></div></section></form>`;
  const input=$("#productImageFile"), preview=$("#productPreview"); input.onchange=async()=>{try{const d=await fileToData(input.files?.[0]);if(d){preview.dataset.image=d;preview.innerHTML=`<img src="${d}" alt="preview">`}}catch(e){toast(e.message);input.value=""}};
  $("#productForm").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);const image=preview.dataset.image!==undefined?preview.dataset.image:(p?.image||"");const body={name:f.get("name"),category:f.get("category"),price:Number(f.get("price")),oldPrice:Number(f.get("oldPrice"))||0,badge:f.get("badge"),delivery:f.get("delivery"),description:f.get("description"),image};try{if(id)await api(`/api/admin/products/${id}`,{method:"PUT",body:JSON.stringify(body)});else await api("/api/admin/products",{method:"POST",body:JSON.stringify(body)});toast(p?"Đã cập nhật sản phẩm":"Đã tạo sản phẩm");go("products")}catch(err){toast(err.message)}};
}
async function deleteProduct(id){if(!confirm("Xóa sản phẩm này?"))return;try{await api(`/api/admin/products/${id}`,{method:"DELETE"});toast("Đã xóa sản phẩm");go("products")}catch(e){toast(e.message)}}

async function renderOrders(){cache.orders=await api("/api/admin/orders");$("#content").innerHTML=`<div class="panel"><div class="page-toolbar"><div class="muted">Cập nhật trạng thái đơn hàng.</div><div class="search"><input id="orderSearch" placeholder="Tìm ID đơn..." oninput="filterRows('orderList','orderSearch')"></div></div><div id="orderList" class="order-list">${cache.orders.map(o=>`<div class="order-row" data-search="${esc((o.id+" "+o.userId).toLowerCase())}"><div><b>${esc(o.id)}</b><div class="row-sub">${fmtDate(o.createdAt)} · User ${esc(o.userId)} · ${money(o.total)}</div><div class="row-sub">${o.items.map(i=>esc(i.name)+" ×"+i.qty).join(" · ")}</div></div><div class="row-actions"><span class="status ${esc(o.status)}">${esc(o.status)}</span><button class="btn small" onclick="changeOrderStatus('${esc(o.id)}')">Trạng thái</button></div></div>`).join("")||`<div class="empty">Chưa có đơn.</div>`}</div></div>`}
async function changeOrderStatus(id){const status=prompt("Nhập trạng thái: paid / processing / completed / cancelled","processing");if(!status)return;try{await api(`/api/admin/orders/${encodeURIComponent(id)}`,{method:"PATCH",body:JSON.stringify({status})});toast("Đã cập nhật đơn");renderOrders()}catch(e){toast(e.message)}}
async function renderTopups(){cache.topups=await api("/api/admin/topups");$("#content").innerHTML=`<div class="panel"><div class="page-toolbar"><div class="muted">Duyệt yêu cầu nạp tiền và cộng số dư.</div><div class="search"><input id="topupSearch" placeholder="Tìm mã nạp..." oninput="filterRows('topupList','topupSearch')"></div></div><div id="topupList" class="order-list">${cache.topups.map(t=>`<div class="topup-row" data-search="${esc((t.id+" "+t.userId).toLowerCase())}"><div><b>${esc(t.id)}</b><div class="row-sub">${fmtDate(t.createdAt)} · User ${esc(t.userId)}</div></div><div class="row-actions"><strong>${money(t.amount)}</strong><span class="status ${esc(t.status)}">${esc(t.status)}</span>${t.status==="pending"?`<button class="btn small" onclick="approveTopup('${esc(t.id)}')">Duyệt</button>`:""}</div></div>`).join("")||`<div class="empty">Chưa có yêu cầu nạp tiền.</div>`}</div></div>`}
async function approveTopup(id){try{await api(`/api/admin/topups/${encodeURIComponent(id)}/approve`,{method:"POST"});toast("Đã duyệt nạp tiền");renderTopups()}catch(e){toast(e.message)}}
function filterRows(listId,inputId){const q=$("#"+inputId).value.toLowerCase();document.querySelectorAll("#"+listId+">*[data-search]").forEach(x=>x.style.display=x.dataset.search.includes(q)?"":"none")}

async function renderDesign(){settings=await api("/api/admin/settings");applyBrand();const cats=(settings.categories||[]).join(", ");const sec=settings.sections||{};const order=settings.homeOrder||["hero","products","trust"];
  $("#content").innerHTML=`<div class="design-layout"><div class="design-stack">
  <section class="design-card"><h3>Thương hiệu</h3><div class="field-grid"><div class="field"><label>Tên shop<input id="shopName" value="${esc(settings.shopName)}"></label></div><div class="field"><label>Tagline<input id="shopTagline" value="${esc(settings.shopTagline)}"></label></div></div><div class="field"><label>Mô tả / SEO<textarea id="metaDescription">${esc(settings.metaDescription)}</textarea></label></div></section>
  <section class="design-card"><h3>Ảnh thương hiệu</h3><div class="image-grid"><div class="image-box"><strong>Logo</strong><input id="logoFile" type="file" accept="image/png,image/jpeg,image/webp,image/gif"><div id="logoPrev" class="preview">${settings.logo?`<img src="${settings.logo}" alt="logo">`:`Chưa có logo`}</div></div><div class="image-box"><strong>Favicon</strong><input id="faviconFile" type="file" accept="image/png,image/jpeg,image/webp,image/gif"><div id="faviconPrev" class="preview">${settings.favicon?`<img src="${settings.favicon}" alt="favicon">`:`Chưa có favicon`}</div></div></div></section>
  <section class="design-card"><h3>Trang chủ</h3><div class="field"><label>Dòng nhỏ<input id="heroEyebrow" value="${esc(settings.heroEyebrow)}"></label></div><div class="field"><label>Tiêu đề<input id="heroTitle" value="${esc(settings.heroTitle)}"></label></div><div class="field"><label>Mô tả<textarea id="heroSubtitle">${esc(settings.heroSubtitle)}</textarea></label></div><div class="field-grid"><div class="field"><label>Nút chính<input id="heroButtonText" value="${esc(settings.heroButtonText)}"></label></div><div class="field"><label>Nút phụ<input id="heroSecondaryText" value="${esc(settings.heroSecondaryText)}"></label></div></div><div class="field"><label>Ảnh Hero / Banner<input id="heroFile" type="file" accept="image/png,image/jpeg,image/webp,image/gif"></label><div id="heroPrev" class="preview">${settings.heroBanner?`<img src="${settings.heroBanner}" alt="hero">`:`Chưa có banner`}</div></div></section>
  <section class="design-card"><h3>Màu giao diện</h3><div class="color-grid">${colorField("primary","Màu chính",settings.primary)}${colorField("accent","Màu nhấn",settings.accent)}${colorField("pageBg","Nền trang",settings.pageBg)}${colorField("cardBg","Nền card",settings.cardBg)}${colorField("text","Màu chữ",settings.text)}${colorField("muted","Chữ phụ",settings.muted)}${colorField("footerBg","Nền footer",settings.footerBg)}</div></section>
  <section class="design-card"><h3>Danh mục</h3><div class="field"><label>Danh mục, cách nhau bằng dấu phẩy<textarea id="categories">${esc(cats)}</textarea></label><div class="helper">Ví dụ: Roblox, Currency, Items, Services, Accounts</div></div></section>
  <section class="design-card"><h3>Liên hệ</h3><div class="field-grid"><div class="field"><label>Email<input id="supportEmail" value="${esc(settings.supportEmail)}"></label></div><div class="field"><label>Số điện thoại<input id="supportPhone" value="${esc(settings.supportPhone)}"></label></div><div class="field"><label>Discord<input id="discord" value="${esc(settings.discord)}"></label></div><div class="field"><label>Facebook<input id="facebook" value="${esc(settings.facebook)}"></label></div></div><div class="field"><label>Telegram<input id="telegram" value="${esc(settings.telegram)}"></label></div></section>
  <section class="design-card"><h3>Bố cục trang chủ</h3><div class="section-toggles"><div class="toggle-row"><div><b>Hero</b><div class="row-sub">Phần giới thiệu/banner đầu trang</div></div><button class="toggle ${sec.hero!==false?"on":""}" data-section="hero" onclick="toggleSection(this)"><i></i></button></div><div class="toggle-row"><div><b>Sản phẩm</b><div class="row-sub">Catalog sản phẩm</div></div><button class="toggle ${sec.products!==false?"on":""}" data-section="products" onclick="toggleSection(this)"><i></i></button></div><div class="toggle-row"><div><b>Trust cards</b><div class="row-sub">Các khối giới thiệu / lợi ích</div></div><button class="toggle ${sec.trust!==false?"on":""}" data-section="trust" onclick="toggleSection(this)"><i></i></button></div></div><div class="order-builder" style="margin-top:12px" id="orderBuilder">${order.map((k,i)=>orderItem(k,i,order.length)).join("")}</div></section>
  <div class="form-actions"><span class="muted">Thay đổi sẽ áp dụng cho shop ngay sau khi lưu.</span><button class="btn primary" onclick="saveDesign(event)">Lưu toàn bộ giao diện</button></div>
  </div><aside class="preview-panel"><div class="design-card"><h3>Preview</h3><p class="muted">Xem nhanh bố cục hiện tại.</p><div id="sitePreview" class="site-preview"></div></div></aside></div>`;
  bindImagePreview("logoFile","logoPrev");bindImagePreview("faviconFile","faviconPrev");bindImagePreview("heroFile","heroPrev");updatePreview();
}
function colorField(name,label,value){return `<label class="color-field"><span>${esc(label)}</span><input id="c_${name}" type="color" value="${esc(value||"#ffffff")}" oninput="updatePreview()"></label>`}
function bindImagePreview(inputId,prevId){const input=$("#"+inputId),prev=$("#"+prevId);input.onchange=async()=>{try{const d=await fileToData(input.files?.[0]);if(d){prev.dataset.image=d;prev.innerHTML=`<img src="${d}" alt="preview">`;if(inputId==="heroFile")updatePreview()}}catch(e){toast(e.message);input.value=""}}}
function toggleSection(btn){btn.classList.toggle("on");updatePreview()}
function orderItem(k,i,len){const label={hero:"Hero",products:"Sản phẩm",trust:"Trust cards"}[k]||k;return `<div class="order-item" data-order="${k}"><div><b>${label}</b></div><div><button type="button" onclick="moveOrder(this,-1)" ${i===0?"disabled":""}>↑</button><button type="button" onclick="moveOrder(this,1)" ${i===len-1?"disabled":""}>↓</button></div></div>`}
function moveOrder(btn,delta){const item=btn.closest(".order-item"),parent=item.parentElement;const all=[...parent.children];const i=all.indexOf(item);const j=i+delta;if(j<0||j>=all.length)return;if(delta<0)parent.insertBefore(item,all[j]);else parent.insertBefore(all[j],item);[...parent.children].forEach((el,i)=>el.querySelectorAll("button").forEach((b,n)=>b.disabled=n===0?i===0:i===parent.children.length-1));updatePreview()}
function currentOrder(){return [...document.querySelectorAll("#orderBuilder .order-item")].map(x=>x.dataset.order)}
function updatePreview(){if(!$("#sitePreview"))return;const pv={primary:$("#c_primary")?.value||settings.primary,accent:$("#c_accent")?.value||settings.accent,card:$("#c_cardBg")?.value||settings.cardBg,bg:$("#c_pageBg")?.value||settings.pageBg};const heroEnabled=document.querySelector('[data-section="hero"]')?.classList.contains("on")!==false;const productsEnabled=document.querySelector('[data-section="products"]')?.classList.contains("on")!==false;const trustEnabled=document.querySelector('[data-section="trust"]')?.classList.contains("on")!==false;const title=$("#heroTitle")?.value||settings.heroTitle;const desc=$("#heroSubtitle")?.value||settings.heroSubtitle;const heroImg=$("#heroPrev")?.dataset.image||settings.heroBanner||"";let html="";for(const k of currentOrder()){if(k==="hero"&&heroEnabled)html+=`<div class="preview-hero" style="--pv-primary:${pv.primary};--pv-accent:${pv.accent};${heroImg?`background-image:linear-gradient(90deg,rgba(9,12,18,.58),rgba(9,12,18,.15)),url('${heroImg.replace(/'/g,"%27")}')`:""}"><small>${esc($("#heroEyebrow")?.value||settings.heroEyebrow)}</small><h4>${esc(title)}</h4><p>${esc(desc)}</p></div>`;if(k==="products"&&productsEnabled){const ps=products.slice(0,4);html+=`<div class="preview-products" style="background:${pv.bg}"><div class="pv-cards">${ps.map(p=>`<div class="pv-card" style="background:${pv.card}"><div class="pv-img">${p.image?`<img src="${p.image}" alt="">`:""}</div><b>${esc(p.name)}</b><div class="pv-price" style="color:${pv.accent}">${money(p.price)}</div></div>`).join("")||`<div class="muted">Thêm sản phẩm để xem preview.</div>`}</div></div>`}if(k==="trust"&&trustEnabled)html+=`<div class="preview-trust"><div class="pv-trust">Ảnh sản phẩm rõ ràng</div><div class="pv-trust">Shop theo thương hiệu của bạn</div><div class="pv-trust">Quản lý ngay trên web</div></div>`}$("#sitePreview").innerHTML=html||`<div class="empty">Chưa bật section nào.</div>`}
async function saveDesign(e){e.preventDefault();try{const body={shopName:$("#shopName").value,shopTagline:$("#shopTagline").value,metaDescription:$("#metaDescription").value,heroEyebrow:$("#heroEyebrow").value,heroTitle:$("#heroTitle").value,heroSubtitle:$("#heroSubtitle").value,heroButtonText:$("#heroButtonText").value,heroSecondaryText:$("#heroSecondaryText").value,supportEmail:$("#supportEmail").value,supportPhone:$("#supportPhone").value,discord:$("#discord").value,facebook:$("#facebook").value,telegram:$("#telegram").value,categories:$("#categories").value.split(",").map(x=>x.trim()).filter(Boolean),sections:{hero:document.querySelector('[data-section="hero"]').classList.contains("on"),products:document.querySelector('[data-section="products"]').classList.contains("on"),trust:document.querySelector('[data-section="trust"]').classList.contains("on")},homeOrder:currentOrder()};for(const [input,prev,key] of [["logoFile","logoPrev","logo"],["faviconFile","faviconPrev","favicon"],["heroFile","heroPrev","heroBanner"]]){const el=$("#"+prev),file=$("#"+input)?.files?.[0];body[key]=file?await fileToData(file):(el?.dataset.image||settings[key]||"")}for(const k of ["primary","accent","pageBg","cardBg","text","muted","footerBg"])body[k]=$("#c_"+k)?.value||settings[k];settings=await api("/api/admin/settings",{method:"PUT",body:JSON.stringify(body)});applyBrand();toast("Đã lưu toàn bộ giao diện");setTimeout(()=>go("design"),250)}catch(err){toast(err.message)}}
boot();
