let products=[];
let cart=JSON.parse(localStorage.getItem("gaming_cart")||"[]");
let token=localStorage.getItem("gaming_token")||"";
let currentUser=null;
let settings={};
const $=s=>document.querySelector(s);
const money=n=>new Intl.NumberFormat("vi-VN").format(Number(n)||0)+"đ";
const fmt=n=>new Intl.NumberFormat("vi-VN").format(Number(n)||0);
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
function toast(msg){const e=$("#toast");e.textContent=msg;e.className="toast show";setTimeout(()=>e.className="toast",2500)}
async function api(url,opts={}){opts.headers={...(opts.headers||{}),"Content-Type":"application/json",...(token?{Authorization:"Bearer "+token}:{})};const r=await fetch(url,opts);const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Có lỗi xảy ra");return d}
function getVariants(p){return Array.isArray(p.variants)&&p.variants.length?p.variants:[{id:"default",name:p.name,price:Number(p.price)||0,image:p.image||"",delivery:p.delivery||"Giao ngay",stock:null}]}
function variantById(p,id){const vs=getVariants(p);return vs.find(v=>String(v.id)===String(id))||vs[0]}
async function boot(){try{settings=await fetch("/api/config").then(r=>r.json());applyTheme();products=await fetch("/api/products").then(r=>r.json());if(token){try{currentUser=await api("/api/me")}catch{token="";localStorage.removeItem("gaming_token")}}renderHeader();renderCart()}catch(e){toast(e.message)}}
function applyTheme(){const root=document.documentElement;for(const [k,v] of Object.entries({primary:settings.primary,accent:settings.accent,pageBg:settings.pageBg,cardBg:settings.cardBg,text:settings.text,muted:settings.muted,footerBg:settings.footerBg})){if(v)root.style.setProperty("--"+k.replace(/[A-Z]/g,m=>"-"+m.toLowerCase()),v)}const bodyFont=["DM Sans","Inter","Manrope","Poppins"].includes(settings.fontBody)?settings.fontBody:"DM Sans";const headFont=["Space Grotesk","DM Sans","Inter","Manrope","Poppins"].includes(settings.fontHeading)?settings.fontHeading:"Space Grotesk";root.style.setProperty("--font-body",`"${bodyFont}",system-ui,sans-serif`);root.style.setProperty("--font-heading",`"${headFont}",system-ui,sans-serif`);document.title=(settings.shopName||"Gaming Shop")+" — Giỏ hàng";$("#shopName").textContent=settings.shopName||"Gaming Shop";$("#shopTagline").textContent=settings.shopTagline||"Marketplace";$("#brandBadge").innerHTML=settings.logo?`<img src="${settings.logo}" alt="">`:(settings.shopName||"G").slice(0,1).toUpperCase();$("#favicon").href=settings.favicon||settings.logo||"data:,"}
function renderHeader(){const count=cart.reduce((s,i)=>s+i.qty,0);$("#cartCount").textContent=count;if(currentUser){$("#accountName").textContent=currentUser.name;$("#accountBalance").textContent=money(currentUser.balance);$("#avatarLetter").textContent=(currentUser.name||"U").slice(0,1).toUpperCase()}else{$("#accountName").textContent="Khách";$("#accountBalance").textContent="Đăng nhập"}}
function renderCart(){if(!cart.length){$("#cartItems").innerHTML=`<div class="checkout-empty"><h3>Giỏ hàng đang trống</h3><p>Bạn chưa chọn sản phẩm nào để thanh toán.</p><a class="empty-action" href="/">Khám phá sản phẩm</a></div>`;$("#itemSummary").textContent="0 sản phẩm";$("#itemCountLabel").textContent="0 sản phẩm";$("#summaryCount").textContent="0 món";$("#orderInfo").innerHTML=`<div class="order-info-item"><span>Trạng thái</span><b>Chưa có sản phẩm</b></div><div class="order-info-item"><span>Thanh toán</span><b>Ví shop</b></div>`;updateSummary(0);$("#checkoutButton").disabled=true;return}
 let total=0;let rows=[];
 for(const i of cart){const p=products.find(x=>x.id===i.id);if(!p)continue;const v=variantById(p,i.variantId);if(!v)continue;const line=Number(v.price)*i.qty;total+=line;rows.push(`<div class="cart-line"><span class="cart-radio"></span><div class="cart-thumb ${v.image||p.image?'':'empty'}">${v.image||p.image?`<img src="${v.image||p.image}" alt="">`:"IMG"}</div><div class="cart-line-main"><b>${esc(p.name)}</b><small>↗ ${esc(v.name)} · ${esc(v.delivery||"Giao ngay")}</small></div><div><div class="cart-line-price">${money(line)}</div><div class="cart-qty-control"><button onclick="changeQty(${p.id},'${esc(String(v.id))}',-1)">−</button><span>${i.qty}</span><button onclick="changeQty(${p.id},'${esc(String(v.id))}',1)">+</button></div></div><button class="remove" onclick="removeItem(${p.id},'${esc(String(v.id))}')">×</button></div>`)}
 $("#cartItems").innerHTML=rows.join("");const count=cart.reduce((s,i)=>s+i.qty,0);$("#itemSummary").textContent=`${count} sản phẩm`;$ ("#itemCountLabel").textContent=`${count} sản phẩm`;$ ("#summaryCount").textContent=`${count} món`;$("#orderInfo").innerHTML=`<div class="order-info-item"><span>Khách hàng</span><b>${currentUser?esc(currentUser.email):"Chưa đăng nhập"}</b></div><div class="order-info-item"><span>Hình thức thanh toán</span><b>Ví shop</b></div><div class="order-info-item"><span>Giao hàng</span><b>Giao ngay / theo từng dòng sản phẩm</b></div><div class="order-info-item"><span>Tự động</span><b>${currentUser?"Kiểm tra số dư trước khi đặt": "Đăng nhập để thanh toán"}</b></div>`;updateSummary(total)}
function updateSummary(total){$("#subtotal").textContent=money(total);$("#discountValue").textContent="0đ";$("#grandTotal").textContent=money(total);$("#walletBalance").textContent=currentUser?money(currentUser.balance):"Chưa đăng nhập";$("#checkoutButton").disabled=!cart.length}
function changeQty(id,vid,delta){const item=cart.find(x=>x.id===id&&String(x.variantId||"default")===String(vid));if(!item)return;item.qty+=delta;if(item.qty<=0)cart=cart.filter(x=>x!==item);saveCart();renderHeader();renderCart()}
function removeItem(id,vid){cart=cart.filter(x=>!(x.id===id&&String(x.variantId||"default")===String(vid)));saveCart();renderHeader();renderCart()}
function clearCart(){if(!cart.length)return;cart=[];saveCart();renderHeader();renderCart();toast("Đã xóa giỏ hàng")}
function saveCart(){localStorage.setItem("gaming_cart",JSON.stringify(cart))}
function refreshPage(){Promise.all([fetch("/api/products").then(r=>r.json()),currentUser?api("/api/me"):Promise.resolve(null)]).then(([ps,u])=>{products=ps;if(u)currentUser=u;renderHeader();renderCart();toast("Đã cập nhật giá")}).catch(e=>toast(e.message))}
function toggleDiscount(){const b=$("#discountBox");b.classList.toggle("hidden");$("#discountArrow").textContent=b.classList.contains("hidden")?"⌄":"⌃"}
function applyDiscount(){const code=$("#discountCode").value.trim();$("#discountMsg").textContent=code?"Mã giảm giá sẽ được xử lý theo cấu hình khuyến mãi của shop.":"Hãy nhập mã giảm giá."}
function goTopup(){if(!currentUser){window.location.href="/?login=1";return}alert("Bạn có thể thêm trang nạp tiền tự động (QR/webhook) ở bước tiếp theo.")}
async function placeOrder(){if(!cart.length)return;if(!currentUser){window.location.href="/?login=1";return}try{$("#checkoutButton").disabled=true;const result=await api("/api/orders",{method:"POST",body:JSON.stringify({items:cart.map(i=>({id:i.id,variantId:i.variantId,qty:i.qty}))})});currentUser=result.user;cart=[];saveCart();renderHeader();$("#checkoutLayout").classList.add("hidden");$("#checkoutSteps").innerHTML=`<div class="step active"><span>🛒</span><b>Giỏ hàng</b></div><div class="step-line"></div><div class="step active"><span>▣</span><b>Xác nhận</b></div><div class="step-line"></div><div class="step active"><span>✓</span><b>Hoàn tất</b></div>`;$("#completedPanel").classList.remove("hidden");$("#completedPanel").innerHTML=`<div class="checkmark">✓</div><h2>Đặt hàng thành công</h2><p>Đơn hàng của bạn đã được tạo và số dư ví đã được trừ.</p><div class="order-id">${esc(result.order.id)}</div><div class="row-actions"><a class="primary-wide" href="/account" style="padding:0 14px">Xem đơn hàng</a><a class="page-back-btn" href="/">Tiếp tục mua sắm</a></div>`;toast("Đặt hàng thành công")}catch(e){$("#checkoutButton").disabled=false;toast(e.message)}}
boot();
